---
  - name: Playbook
    hosts: localhost
    tasks:
      - name: Create a jenkins job
        community.general.jenkins_job:
          config: "{{ lookup('file', 'templates/job.xml') }}"
          name: init_webtools
          password: 12qwaszx
          url: http://localhost:8080
          user: admin

